### ISSUE TITLE
drm

### ISSUE THREAD

**Issue by harkaman** [maurossi/drm#1]
I am building Nougat-x86, sync from OSDN.  I want to use kernel 4,15 and mesa, 18.1. Need help.

First I get thi issue.
https://imgur.com/a/JYl8W

I leave as it is and then make build, tried bot 32/64bit

build/envsetup.sh
lunch android_x86_64-userdebug
lunch android_x86-userdebug
m -j8 iso_img

And get this error

```
including ./system/webservd/Android.mk ...
PRODUCT_COPY_FILES frameworks/base/compiled-classes-phone:system/etc/compiled-classes ignored.
build/core/binary.mk:925: warning: overriding commands for target `out/target/product/x86/obj/STATIC_LIBRARIES/libv8_intermediates/src/base/atomicops_internals_x86_gcc.o'
build/core/binary.mk:925: warning: ignoring old commands for target `out/target/product/x86/obj/STATIC_LIBRARIES/libv8_intermediates/src/base/atomicops_internals_x86_gcc.o'
device/generic/common/build/tasks/kernel.mk:99: warning: overriding commands for target `out/target/product/x86/kernel'
build/core/tasks/kernel.mk:99: warning: ignoring old commands for target `out/target/product/x86/kernel'
device/generic/common/build/tasks/system.mk:8: warning: overriding commands for target `out/target/product/x86/system.sfs'
build/core/Makefile:1187: warning: ignoring old commands for target `out/target/product/x86/system.sfs'
Starting build with ninja
ninja: Entering directory `.'
ninja: error: 'frameworks/base/config/compiled-classes-phone', needed by 'out/target/product/x86/system/etc/compiled-classes', missing and no known rule to make it
build/core/ninja.mk:148: recipe for target 'ninja_wrapper' failed
make: *** [ninja_wrapper] Error 1
make: Leaving directory '/home/harkamanshivakoti/android-x86'

```

**Comment by maurossi** [comment]
the repo to be added with 'git remote add'
is https://github.com/maurossi/drm

**Comment by harkaman** [comment]
I did like this, but it was not working yesterday:

cd ~/android-x86/external/libdrm/
git remote add maurossi https://github.com/maurossi/drm
git fetch maurossi 2.4.89_android-x86
git checkout FETCH_HEAD

**Comment by maurossi** [comment]
once remote was added with wrong url, it has to be removed with:

`git remote rm maurossi`

at that point command will work

**Comment by harkaman** [comment]
I have successfully added drm and drm hwcomposer. no error to add these too. but other i get error,
But other cant. what I am doing wrong?

I am building Nougat-x86. this is how I am adding from your github:

```
cd ~/android-x86/kernel
git remote add maurossi https://github.com/maurossi/linux.git
git fetch maurossi
git checkout maurossi/kernel-4.15

cd ~/android-x86/external/llvm
git remote add maurossi https://github.com/maurossi/llvm.git
git fetch maurossi
git checkout maurossi/nougat-x86_llvm60

cd ~/android-x86/external/mesa
git remote add maurossi https://github.com/maurossi/mesa.git
git fetch maurossi
git checkout maurossi/18.1.0-devel_w04

cd ~/android-x86/external/libdrm/
git remote add maurossi https://github.com/maurossi/drm.git
git fetch maurossi
git checkout maurossi/2.4.89_android-x86

cd ~/android-x86/external/drm_hwcomposer/
git remote add maurossi https://github.com/maurossi/drm_hwcomposer.git
git fetch maurossi
git checkout maurossi/nougat-x86_rotate_hack

. build/envsetup.sh
lunch android_x86-userdebug
lunch android_x86_64-userdebug
m -j8 iso_img

```

**Comment by maurossi** [comment]
Hi,
since this has nothing to do with libdrm repo,
this thread has to be closed, right?

The errors you are seeying are due to having replaced external/llvm with newer version than the one bundled with AOSP/android-x86,
the AOSP codebase does not support that type of upgrade.

llvm60 ( or llvm50 ) need to be build as additional project e.g. external/llvm60 (or external/llvm50)

Here follows procedure for llvm60, which may be converted for llvm50 if needed:

cd external
git clone https://github.com/maurossi/llvm llvm60
cd llvm60
git fetch origin oreo-x86_llvm60 [or nougat-x86_llvm60, even if oreo-x86_llvm60 should also work with nougat-x86/7.1]
git checkout FETCH_HEAD

The llvm60 branches  for nougat-x86 [1] and oreo-x86 [2] have both been tested and can be rebased to llvm-mirror/release_60

[1] https://github.com/maurossi/llvm/commits/nougat-x86_llvm60

[2] https://github.com/maurossi/llvm/commits/oreo-x86_llvm60

git remote add llvm-mirror https://github.com/llvm-mirror/llvm
git fetch llvm-mirror release_60
git rebase llvm-mirror/release_60

This will allow full build of AOSP with AS-IS libLLVM and create an ad hoc shared library libLLVM60 to be only used as dependency for mesa.
In order to change the dependency from libLLVM to libLLVM60  in external/mesa/Android.mk and HAVE_LLVM variable accordingly set to 0x0600 for nougat-x86 (android version 7) or oreo-x86 (android version 8).

The build will require  20 Gbytes of additional disk space, as all libLLVM* static libraries were all renamed to libLLVM60* 

Cheers a thread closed, please use android-x86 forum for these kind of experiments
Mauro
